### ISSUE TITLE
Cant find the  .pause() and .resume() function for the library

### ISSUE THREAD

**Issue by drexlar5** [danielgindi/node-csv-reader#14]
I cant find the pause and resume function. I think It will be an essential addition to this library so that users will be able to take action on a particular row of their choosing before resuming reading from file stream

**Comment by danielgindi** [comment]
This is how `node.js` works, `pause`/`resume` is [out of the box](https://nodejs.org/api/stream.html#stream_readable_pause).

**Comment by drexlar5** [comment]
Thanks, Gotten what i needed.
