### ISSUE TITLE
Feature request - skip header line

### ISSUE THREAD

**Issue by bigman73** [danielgindi/node-csv-reader#3]
If the data file has a header in the first row then have an option to skip it

For example:
NAME, AGE
John Smith, 45

Row 1 should not be processed if skipHeader: true

**Comment by danielgindi** [comment]
Do you want to send a PR? :-)

**Comment by bigman73** [comment]
https://github.com/danielgindi/node-csv-reader/pull/4

**Comment by bigman73** [comment]
@danielgindi Hi, the PR has been submitted 3 days ago. Please merge it in.

**Comment by danielgindi** [comment]
Thank you :-)
Merged in and published!
