### ISSUE TITLE
Export other types

### ISSUE THREAD

**Issue by tgbv** [danielgindi/node-csv-reader#31]
It would be useful if other types from package are exported as well, eg: `Line`, `DataTypes`, etc.

Do you consider such idea?

**Comment by tgbv** [comment]
In case you agree, here's a PR: https://github.com/danielgindi/node-csv-reader/pull/32

Do you think we should also force git LF conversion for source files? I don't see a .gitattributes doing that.

**Comment by danielgindi** [comment]
Thank you for the PR :-)
I do not believe we need LF conversion in a gitattributes file, as there's a reasonable set of default settings that ships with most git distros these days.
