### ISSUE TITLE
trim logic doesn't affect both ends of the string

### ISSUE THREAD

**Issue by drewed** [danielgindi/node-csv-reader#9]
Your regex `/^\s+|\s+$/` will only trim whitespace at the beginning _or_ the end of the string but not both.  Is there a reason you're not using [String.prototype.trim()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim)?

**Comment by danielgindi** [comment]
Just an oversight!
